Document: pilight-cc
Title: Debian pilight-cc Manual
Author: <insert document author here>
Abstract: This manual describes what pilight-cc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pilight-cc/pilight-cc.sgml.gz

Format: postscript
Files: /usr/share/doc/pilight-cc/pilight-cc.ps.gz

Format: text
Files: /usr/share/doc/pilight-cc/pilight-cc.text.gz

Format: HTML
Index: /usr/share/doc/pilight-cc/html/index.html
Files: /usr/share/doc/pilight-cc/html/*.html
